### ISSUE TITLE
server: manejar la comunicación entre servers cuando estos migran

### ISSUE THREAD

**Issue by msmendoza** [MrEarle/T2-SSDD-G6#11]
Se sugiere mantener o actualizar la lista de los servers en el DNS.

**Comment by MrEarle** [comment]
Se me ocurren 2 ideas para hacerlo.

# Idea 1

Que funcione como funcionan los clientes.

Cuando el server A migra:
1. Avisa al server B que va a migrar, por lo que debe encolar sus mensajes
2. Hace la migracion (o le dice a B que se despause si no puede)
3. Decirle a B que se reconecte

# Idea 2

Hacer que la comunicacion de pedir el proximo indice sea por socket normal, como en el DNS

Cada vez que se pide el next_index al otro server:

1. Pedir IP del otro server al DNS
2. Conectarse por socket
3. Pedir next index
4. Desconectarse

Yo creo que la idea 1 es más complicada de implementar bien, pero disminuye el overhead de mandar mensajes. La idea 2 me tinca más fácil de implementar, pero requiere hacer una conexión al otro server cada vez que se manda un mensaje.
